### ISSUE TITLE
How to retrieve RCON GetChat()

### ISSUE THREAD

**Issue by Reginherus** [Sp1rit/ArkRcon#2]
Hey Sp1rit,

Been using this for a custom program to maintain the server I run. It works AMAZINGLY! Thank you for all your time you put into this. 

One quick question, How do I retrieve the ChatLog when calling GetChat() command?

When I leave it is string chat = response?Body I get "Server message received but no response"

On the side, I am using the executable that you posted with the solution and it gets the chat no problem. Do you happen to have to solution to the executable?

Cause I don't mind digging through the code myself to figure it out. Once again, thank you~

**Comment by Sp1rit** [comment]
Hey,

you can find the tool i created this lib for in my repositories. It's called ArkRemoteAdmin.

But it's basically just a simple check. If ARK responded with the message you mentioned there are no new chat messages:

```csharp
if (e.Response.Trim() != "Server received, But no response!!")
 ```

**Comment by Reginherus** [comment]
I can't believe I didn't notice either one of those... Now is GetChat registered server side? So if I run an RCON client that gets chat every 30 seconds, I won't be able to GetChat on a secondary app right afterwards? Is there anyway not to clear Chat when GetChat is called?

Thanks again.

**Comment by Sp1rit** [comment]
No there is not. ARKs RCON protocol is pretty shitty. I have tried to replace it but there is no chance with the current dev tool they provide.

**Comment by Natemiller24** [comment]
Hey Phillip,

Figured I'd carry the convo over here since the next part is irrelevant.
Have you seen the Ark Plugin that came out? It's called ArkAPI and has
various different plugins that you can push into it. One of them is the
extended RCON which I use on my server and have even pushed in the commands
to your existing RCON library.

If you haven't and are interested in what I'm referring too, here is the
link:
https://survivetheark.com/index.php?/forums/topic/128053-ark-server-beyond-api-alpha-v08/
